[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$sLZWao2x1vrfey9lrPV.jw$5x9lurkCHB39yEv1.3LeeVWcV3hOaLZjxwSKTAfOfS2TWDxTVgTVcIkHmuQa9dSvCDuvUNBbrUww5d3m3os/Cw
list_db = True

